---
kind: "pipeline"
type: "docker"
name: "php 7.4 / prefer-stable"

steps:
  - name: "restore_cache"
    image: "drillster/drone-volume-cache"
    settings:
      restore: true
      mount:
        - "./vendor"
    volumes:
      - name: "cache_php74_stable"
        path: "/cache-php74-stable"

  - name: "prepare_php"
    image: "jkniest/docker-testing-php:1"
    commands:
      - "composer update --prefer-stable"
    depends_on:
      - "restore_cache"

  - name: "rebuild_cache"
    image: "drillster/drone-volume-cache"
    settings:
      rebuild: true
      mount:
        - "./vendor"
    volumes:
      - name: "cache_php74_stable"
        path: "/cache-php74-stable"
    depends_on:
      - "prepare_php"

  - name: "test_phpspec"
    image: "jkniest/docker-testing-php:1"
    commands:
      - "./vendor/bin/phpspec run --config phpspec_coverage.yml"
      - "php test-coverage.php"
    depends_on:
      - "rebuild_cache"

  - name: "test_phpcsfixer"
    image: "jkniest/docker-testing-php:1"
    commands:
      - "./vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.php --dry-run"
    depends_on:
      - "rebuild_cache"

  - name: "test_phpstan"
    image: "jkniest/docker-testing-php:1"
    commands:
      - "./vendor/bin/phpstan analyse src --level=max"
    depends_on:
      - "rebuild_cache"

volumes:
  - name: cache_php74_stable
    host:
      path: /tmp/drone/cache-php74-stable

---
kind: "pipeline"
type: "docker"
name: "php 7.4 / prefer-lowest"

steps:
  - name: "restore_cache"
    image: "drillster/drone-volume-cache"
    settings:
      restore: true
      mount:
        - "./vendor"
    volumes:
      - name: "cache_php74_lowest"
        path: "/cache-php74-lowest"

  - name: "prepare_php"
    image: "jkniest/docker-testing-php:1"
    commands:
      - "composer update --prefer-lowest"
    depends_on:
      - "restore_cache"

  - name: "rebuild_cache"
    image: "drillster/drone-volume-cache"
    settings:
      rebuild: true
      mount:
        - "./vendor"
    volumes:
      - name: "cache_php74_lowest"
        path: "/cache-php74-lowest"
    depends_on:
      - "prepare_php"

  - name: "test_phpspec"
    image: "jkniest/docker-testing-php:1"
    commands:
      - "./vendor/bin/phpspec run --config phpspec_coverage.yml"
      - "php test-coverage.php"
    depends_on:
      - "rebuild_cache"

  - name: "test_phpcsfixer"
    image: "jkniest/docker-testing-php:1"
    commands:
      - "./vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.php --dry-run"
    depends_on:
      - "rebuild_cache"

  - name: "test_phpstan"
    image: "jkniest/docker-testing-php:1"
    commands:
      - "./vendor/bin/phpstan analyse src --level=max"
    depends_on:
      - "rebuild_cache"

volumes:
  - name: cache_php74_lowest
    host:
      path: /tmp/drone/cache-php74-lowest

---
kind: "pipeline"
type: "docker"
name: "php 8.0 / prefer-stable"

steps:
  - name: "restore_cache"
    image: "drillster/drone-volume-cache"
    settings:
      restore: true
      mount:
        - "./vendor"
    volumes:
      - name: "cache_php80_stable"
        path: "/cache-php80-stable"

  - name: "prepare_php"
    image: "jkniest/docker-testing-php:2"
    commands:
      - "composer update --prefer-stable"
    depends_on:
      - "restore_cache"

  - name: "rebuild_cache"
    image: "drillster/drone-volume-cache"
    settings:
      rebuild: true
      mount:
        - "./vendor"
    volumes:
      - name: "cache_php80_stable"
        path: "/cache-php80-stable"
    depends_on:
      - "prepare_php"

  - name: "test_phpspec"
    image: "jkniest/docker-testing-php:2"
    commands:
      - "./vendor/bin/phpspec run --config phpspec_coverage.yml"
      - "php test-coverage.php"
    depends_on:
      - "rebuild_cache"

  - name: "test_phpcsfixer"
    image: "jkniest/docker-testing-php:2"
    commands:
      - "./vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.php --dry-run"
    depends_on:
      - "rebuild_cache"

  - name: "test_phpstan"
    image: "jkniest/docker-testing-php:2"
    commands:
      - "./vendor/bin/phpstan analyse src --level=max"
    depends_on:
      - "rebuild_cache"

volumes:
  - name: cache_php80_stable
    host:
      path: /tmp/drone/cache-php80-stable

---
kind: "pipeline"
type: "docker"
name: "php 8.0 / prefer-lowest"

steps:
  - name: "restore_cache"
    image: "drillster/drone-volume-cache"
    settings:
      restore: true
      mount:
        - "./vendor"
    volumes:
      - name: "cache_php80_lowest"
        path: "/cache-php80-lowest"

  - name: "prepare_php"
    image: "jkniest/docker-testing-php:2"
    commands:
      - "composer update --prefer-lowest"
    depends_on:
      - "restore_cache"

  - name: "rebuild_cache"
    image: "drillster/drone-volume-cache"
    settings:
      rebuild: true
      mount:
        - "./vendor"
    volumes:
      - name: "cache_php80_lowest"
        path: "/cache-php80-lowest"
    depends_on:
      - "prepare_php"

  - name: "test_phpspec"
    image: "jkniest/docker-testing-php:2"
    commands:
      - "./vendor/bin/phpspec run --config phpspec_coverage.yml"
      - "php test-coverage.php"
    depends_on:
      - "rebuild_cache"

  - name: "test_phpcsfixer"
    image: "jkniest/docker-testing-php:2"
    commands:
      - "./vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.php --dry-run"
    depends_on:
      - "rebuild_cache"

  - name: "test_phpstan"
    image: "jkniest/docker-testing-php:2"
    commands:
      - "./vendor/bin/phpstan analyse src --level=max"
    depends_on:
      - "rebuild_cache"

volumes:
  - name: cache_php80_lowest
    host:
      path: /tmp/drone/cache-php80-lowest

---
kind: "pipeline"
type: "docker"
name: "php 8.1 / prefer-stable"

steps:
  - name: "restore_cache"
    image: "drillster/drone-volume-cache"
    settings:
      restore: true
      mount:
        - "./vendor"
    volumes:
      - name: "cache_php81_stable"
        path: "/cache-php81-stable"

  - name: "prepare_php"
    image: "jkniest/docker-testing-php:3"
    commands:
      - "composer update --prefer-stable"
    depends_on:
      - "restore_cache"

  - name: "rebuild_cache"
    image: "drillster/drone-volume-cache"
    settings:
      rebuild: true
      mount:
        - "./vendor"
    volumes:
      - name: "cache_php81_stable"
        path: "/cache-php81-stable"
    depends_on:
      - "prepare_php"

  - name: "test_phpspec"
    image: "jkniest/docker-testing-php:3"
    commands:
      - "./vendor/bin/phpspec run --config phpspec_coverage.yml"
      - "php test-coverage.php"
    depends_on:
      - "rebuild_cache"

  - name: "test_phpcsfixer"
    image: "jkniest/docker-testing-php:3"
    commands:
      - "./vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.php --dry-run"
    depends_on:
      - "rebuild_cache"

  - name: "test_phpstan"
    image: "jkniest/docker-testing-php:3"
    commands:
      - "./vendor/bin/phpstan analyse src --level=max"
    depends_on:
      - "rebuild_cache"

volumes:
  - name: cache_php81_stable
    host:
      path: /tmp/drone/cache-81-stable

---
kind: "pipeline"
type: "docker"
name: "php 8.1 / prefer-lowest"

steps:
  - name: "restore_cache"
    image: "drillster/drone-volume-cache"
    settings:
      restore: true
      mount:
        - "./vendor"
    volumes:
      - name: "cache_php81_lowest"
        path: "/cache-php81-lowest"

  - name: "prepare_php"
    image: "jkniest/docker-testing-php:3"
    commands:
      - "composer update --prefer-lowest"
    depends_on:
      - "restore_cache"

  - name: "rebuild_cache"
    image: "drillster/drone-volume-cache"
    settings:
      rebuild: true
      mount:
        - "./vendor"
    volumes:
      - name: "cache_php81_lowest"
        path: "/cache-php81-lowest"
    depends_on:
      - "prepare_php"

  - name: "test_phpspec"
    image: "jkniest/docker-testing-php:3"
    commands:
      - "./vendor/bin/phpspec run --config phpspec_coverage.yml"
      - "php test-coverage.php"
    depends_on:
      - "rebuild_cache"

  - name: "test_phpcsfixer"
    image: "jkniest/docker-testing-php:3"
    commands:
      - "./vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.php --dry-run"
    depends_on:
      - "rebuild_cache"

  - name: "test_phpstan"
    image: "jkniest/docker-testing-php:3"
    commands:
      - "./vendor/bin/phpstan analyse src --level=max"
    depends_on:
      - "rebuild_cache"

volumes:
  - name: cache_php81_lowest
    host:
      path: /tmp/drone/cache-81-lowest
---
kind: "pipeline"
type: "docker"
name: "docs"

steps:
  - name: "restore_cache"
    image: "drillster/drone-volume-cache"
    settings:
      restore: true
      mount:
        - "./node_modules"
    volumes:
      - name: "cache"
        path: "/cache"

  - name: "prepare_node"
    image: "node:16"
    commands:
      - "npm ci"
    depends_on:
      - "restore_cache"

  - name: "rebuild_cache"
    image: "drillster/drone-volume-cache"
    settings:
      rebuild: true
      mount:
        - "./node_modules"
    volumes:
      - name: "cache"
        path: "/cache"
    depends_on:
      - "prepare_node"

  - name: "build documentation"
    image: "node:16"
    commands:
      - "npm run docs:build"
    depends_on:
      - "rebuild_cache"

volumes:
  - name: cache
    host:
      path: /tmp/drone/cache
