---
kind: "pipeline"
type: "docker"
name: "php 7.4 / prefer-stable"

steps:
  - name: "restore_cache"
    image: "drillster/drone-volume-cache"
    settings:
      restore: true
      mount:
        - "./vendor"
    volumes:
      - name: "cache"
        path: "/cache"

  - name: "prepare_php"
    image: "jkniest/docker-testing-php:1"
    commands:
      - "rm composer.lock"
      - "composer update --prefer-stable"
    depends_on:
      - "restore_cache"

  - name: "rebuild_cache"
    image: "drillster/drone-volume-cache"
    settings:
      rebuild: true
      mount:
        - "./vendor"
    volumes:
      - name: "cache"
        path: "/cache"
    depends_on:
      - "prepare_php"

  - name: "test_phpspec"
    image: "jkniest/docker-testing-php:1"
    commands:
      - "./vendor/bin/phpspec run --config phpspec_coverage.yml"
      - "php test-coverage.php"
    depends_on:
      - "rebuild_cache"

  - name: "test_phpcsfixer"
    image: "jkniest/docker-testing-php:1"
    commands:
      - "./vendor/bin/php-cs-fixer fix --config=.php_cs --allow-risky=yes --dry-run src/ spec/"
    depends_on:
      - "rebuild_cache"

  - name: "test_phpstan"
    image: "jkniest/docker-testing-php:1"
    commands:
      - "./vendor/bin/phpstan analyse src --level=max"
    depends_on:
      - "rebuild_cache"

volumes:
  - name: cache
    host:
      path: /tmp/drone/cache

---
kind: "pipeline"
type: "docker"
name: "php 7.4 / prefer-lowest"

steps:
  - name: "restore_cache"
    image: "drillster/drone-volume-cache"
    settings:
      restore: true
      mount:
        - "./vendor"
    volumes:
      - name: "cache"
        path: "/cache"

  - name: "prepare_php"
    image: "jkniest/docker-testing-php:1"
    commands:
      - "rm composer.lock"
      - "composer update --prefer-lowest"
    depends_on:
      - "restore_cache"

  - name: "rebuild_cache"
    image: "drillster/drone-volume-cache"
    settings:
      rebuild: true
      mount:
        - "./vendor"
    volumes:
      - name: "cache"
        path: "/cache"
    depends_on:
      - "prepare_php"

  - name: "test_phpspec"
    image: "jkniest/docker-testing-php:1"
    commands:
      - "./vendor/bin/phpspec run --config phpspec_coverage.yml"
      - "php test-coverage.php"
    depends_on:
      - "rebuild_cache"

  - name: "test_phpcsfixer"
    image: "jkniest/docker-testing-php:1"
    commands:
      - "./vendor/bin/php-cs-fixer fix --config=.php_cs --allow-risky=yes --dry-run src/ spec/"
    depends_on:
      - "rebuild_cache"

  - name: "test_phpstan"
    image: "jkniest/docker-testing-php:1"
    commands:
      - "./vendor/bin/phpstan analyse src --level=max"
    depends_on:
      - "rebuild_cache"

volumes:
  - name: cache
    host:
      path: /tmp/drone/cache

---
kind: "pipeline"
type: "docker"
name: "php 8.0 / prefer-stable"

steps:
  - name: "restore_cache"
    image: "drillster/drone-volume-cache"
    settings:
      restore: true
      mount:
        - "./vendor"
    volumes:
      - name: "cache"
        path: "/cache"

  - name: "prepare_php"
    image: "jkniest/docker-testing-php:2"
    commands:
      - "rm composer.lock"
      - "composer update --prefer-stable"
    depends_on:
      - "restore_cache"

  - name: "rebuild_cache"
    image: "drillster/drone-volume-cache"
    settings:
      rebuild: true
      mount:
        - "./vendor"
    volumes:
      - name: "cache"
        path: "/cache"
    depends_on:
      - "prepare_php"

  - name: "test_phpspec"
    image: "jkniest/docker-testing-php:2"
    commands:
      - "./vendor/bin/phpspec run --config phpspec_coverage.yml"
      - "php test-coverage.php"
    depends_on:
      - "rebuild_cache"

  - name: "test_phpcsfixer"
    image: "jkniest/docker-testing-php:2"
    commands:
      - "./vendor/bin/php-cs-fixer fix --config=.php_cs --allow-risky=yes --dry-run src/ spec/"
    depends_on:
      - "rebuild_cache"

  - name: "test_phpstan"
    image: "jkniest/docker-testing-php:2"
    commands:
      - "./vendor/bin/phpstan analyse src --level=max"
    depends_on:
      - "rebuild_cache"

volumes:
  - name: cache
    host:
      path: /tmp/drone/cache

---
kind: "pipeline"
type: "docker"
name: "php 8.0 / prefer-lowest"

steps:
  - name: "restore_cache"
    image: "drillster/drone-volume-cache"
    settings:
      restore: true
      mount:
        - "./vendor"
    volumes:
      - name: "cache"
        path: "/cache"

  - name: "prepare_php"
    image: "jkniest/docker-testing-php:2"
    commands:
      - "rm composer.lock"
      - "composer update --prefer-lowest"
    depends_on:
      - "restore_cache"

  - name: "rebuild_cache"
    image: "drillster/drone-volume-cache"
    settings:
      rebuild: true
      mount:
        - "./vendor"
    volumes:
      - name: "cache"
        path: "/cache"
    depends_on:
      - "prepare_php"

  - name: "test_phpspec"
    image: "jkniest/docker-testing-php:2"
    commands:
      - "./vendor/bin/phpspec run --config phpspec_coverage.yml"
      - "php test-coverage.php"
    depends_on:
      - "rebuild_cache"

  - name: "test_phpcsfixer"
    image: "jkniest/docker-testing-php:2"
    commands:
      - "./vendor/bin/php-cs-fixer fix --config=.php_cs --allow-risky=yes --dry-run src/ spec/"
    depends_on:
      - "rebuild_cache"

  - name: "test_phpstan"
    image: "jkniest/docker-testing-php:2"
    commands:
      - "./vendor/bin/phpstan analyse src --level=max"
    depends_on:
      - "rebuild_cache"

volumes:
  - name: cache
    host:
      path: /tmp/drone/cache
