name: scan
on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    name: Sonarqube
    runs-on: ubuntu-latest

    steps:
      # We will always use the oldest supported version of PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache composer dependencies
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-8.2-strategy-lowest
          restore-keys: |
            ${{ runner.os }}-php-8.2-strategy-lowest

      - name: Install dependencies
        run: 'composer update -W --prefer-lowest --no-ansi --no-interaction --no-progress --optimize-autoloader'

      - name: Run PHPspec
        run: './vendor/bin/phpspec run --config phpspec_coverage.yml'

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
